services:
  jackett:
    image: linuxserver/jackett:0.24.2151@sha256:bb3c2c158bcf409389a442def31c96fb94db90cf75749d56b234032203890b29
    container_name: jackett
    restart: unless-stopped
    ports:
      - 8031:9117
    volumes:
      - jackett_config:/config
    environment:
      - PUID=911
      - PGID=1000
      - TZ=Europe/Paris
      - JACKETT_KEY=${JACKETT_API_KEY:-}
    # links:
    #   - flaresolverr

  radarr:
    image: linuxserver/radarr:6.2.1
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - radarr_config:/config
      - ./data:/data
    ports:
      - 8032:7878
    restart: unless-stopped
    links:
      - jackett
      - uploader

  sonarr:
    image: linuxserver/sonarr:4.0.19
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - sonarr_config:/config
      - ./data:/data
    ports:
      - 8033:8989
    restart: unless-stopped
    links:
      - jackett
      - uploader

  # flaresolverr:
  #   image: flaresolverr/flaresolverr:v3.5.0
  #   container_name: flaresolverr
  #   environment:
  #     - LOG_LEVEL=${LOG_LEVEL:-info}
  #     - LOG_HTML=${LOG_HTML:-false}
  #     - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
  #     - TZ=Europe/London
  #   restart: unless-stopped

  uploader:
    container_name: torrent_uploader
    build: .
    command: npm run uploader
    environment:
      - ALLDEBRID_API_KEY=${ALLDEBRID_API_KEY}
    restart: unless-stopped
    volumes:
      - ./data:/data

  bootstrap:
    profiles:
      - bootstrap
    container_name: torrent_bootstrap
    build: .
    command: npm run bootstrap
    environment:
      - JACKETT_API_KEY=${JACKETT_API_KEY:-}
      - JACKETT_BASE_URL=http://jackett:9117
      - RADARR_BASE_URL=http://radarr:7878
      - RADARR_INDEXER_MIN_SEEDERS=${RADARR_INDEXER_MIN_SEEDERS:-5}
      - SONARR_BASE_URL=http://sonarr:8989
      - SONARR_INDEXER_MIN_SEEDERS=${SONARR_INDEXER_MIN_SEEDERS:-1}
      - ROOT_FOLDER=/data/files
      - TORRENT_FOLDER=/data/torrents/
      - WATCH_FOLDER=/data/completed/
      - WEBHOOK_URL=http://uploader:3000
    restart: 'no'
    depends_on:
      - jackett
      - radarr
      - sonarr
    volumes:
      - jackett_config:/config/jackett
      - radarr_config:/config/radarr:ro
      - sonarr_config:/config/sonarr:ro
      - ./data:/data

volumes:
  jackett_config:
  radarr_config:
  sonarr_config:
